server:
  port: 8002

dubbo:
  application:
    ##### 注册服务的名称
    name: group-web
  ##### 注册中心地址
  registry:
    address: zookeeper://39.106.90.140:2181
  ##### 调用服务超时时间
  consumer:
    timeout: 10000
# Swagger界面内容配置
swagger:
  title: DevPlatform API接口文档
  description: DevPlatform Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://gitee.com
  contact:
    name: Meng FanChun
    url: https://gitee.com/
    email: 522183973@qq.com