server:
  port: 9003

dubbo:
  application:
  ###########注册到注册中心的名称############
    name: user-service
  ###########采用协议和端口号################
  protocol:
  ###########采用dubbo协议####################
    name: dubbo
  ###########发布dubbo端口号为20880###########
    port: 20882
  registry:
  ###########注册中心地址#####################
    address: zookeeper://192.168.230.128:2181
  scan:
  ############实现类扫包范围###################
    base-packages: com.jindumooc.user.service.impl